source 'https://rubygems.org'
gem 'on_irc'
gem 'promise'
gem 'pry'
gem 'json'
gem 'configru', '~> 0.5'
gem 'nokogiri'
gem 'backports'
gem 'ansirc'
gem 'github-linguist', '~> 2.2'
gem 'sinatra' # Statistics web interface.
gem 'evalso'
gem 'httparty', '~> 0.11.0'
gem 'rubyheap', '>= 0.1.3'
