source 'https://rubygems.org'
gem 'on_irc'
gem 'promise'
gem 'rvm'
gem 'pry'
gem 'json'
gem 'configru', '~> 0.5'
gem 'nokogiri'
gem 'backports'
gem 'ansirc'
gem 'github-linguist', '~> 2.2'
gem 'sinatra' # Statistics web interface.
gem 'evalso'
gem 'httparty'
gem 'rubyheap'
