require 'stringio'

$time_limit = 5 # Time limit for execution

class SafeEval
  attr_reader :error
  def initialize(chroot=nil)
    unless chroot.nil?
      Dir.mkdir(chroot) if !File.directory?(chroot)
      @chroot = chroot
    end
  end

  def out_to_string(stdout=StringIO.new)
    old_stdout = $stdout.to_i
    begin
      $stdout = stdout
      yield
    ensure
      $stdout = IO.new(old_stdout)
    end
    stdout.string
  end

  def eval(cmd)
    output = nil
    error = nil
    result = nil
    command = <<-EOF
      $SAFE=3
      #{cmd}
    EOF

    begin
      result = ::Kernel.eval(command, TOPLEVEL_BINDING)
    rescue Exception, SecurityError => e
      @error = e
    end

    if !error.to_s.empty?
      @error
    elsif !output.to_s.empty?
      output
    else
      result
    end
  end

  def run(code, filename)
    save_file(code, filename)
    run_file(filename)
  end

  def run_file(filename)
    random = nil
    output = ''

    begin
      thread = Thread.new do
        random = rand
        output = `sudo ruby #{filename.inspect} #{random}`
      end
    rescue Exception => e
      error = e
    ensure
      $stdout = STDOUT
    end

    1.upto($time_limit+1).each do |i|
      id = nil
      id_parts = `ps aux | grep -v grep | grep -i ruby | grep -i nobody | grep -i "#{random}"`.split(' ')
      id = id_parts[1].to_i unless id_parts.include?("<defunct>")

      if thread.alive? && i > $time_limit && id != 0
        puts id
        `sudo kill -9 #{id}`
        thread.kill
        error = "Execution took longer than #{$time_limit} seconds, exiting."
        break
      elsif i > $time_limit || !thread.alive?
        break
      end
      sleep 1
    end

    if !error.nil?
      error
    elsif !output.inspect.empty? && (!output.inspect == '""' && !thread.value.inspect.empty?)
      output
    else
      thread.value
    end
  end

  def save_file(code, filename)
    File.open(filename, "w") do |f|
      f.write(generate_script(code))
    end
  end

  def generate_script(code)
      tmp = <<-EOF
# Generated by Nick Markwell's (duckinator) SafeEval class on #{Time.now}

require 'stringio'
require 'etc'
require #{__FILE__.inspect}

nobody_uid = Etc.getpwnam('nobody').uid
nobody_gid = Etc.getgrnam('nobody').gid
Dir.chroot(#{@chroot.inspect})
Dir.chdir("/")

Process.initgroups('nobody', nobody_gid)
Process::GID.change_privilege(nobody_gid)
Process::UID.change_privilege(nobody_uid)

if Process.uid != nobody_uid
  puts "Error setting up chroot"
  exit
end

cmd = #{code.inspect}

output = ''
result = ''
error = nil

begin
  seval = SafeEval.new
  output = seval.out_to_string do
    result = seval.eval cmd
  end
rescue Exception => e
  error = e
ensure
  $stdout = STDOUT
end

error ||= seval.error

begin
  if !error.nil? && output.empty?
    puts "\#{error.class}: \#{error.message}"
  elsif !output.empty?
    puts output
  else
    puts result.inspect
  end
rescue => e
  puts "\#{e.class}: \#{e.message}"
end
      EOF
  end
end

